import coffee1 from "../assets/images/coffee-img/coffee-1.jpg";
import coffee2 from "../assets/images/coffee-img/coffee-2.jpg";
import coffee3 from "../assets/images/coffee-img/coffee-3.jpg";
import coffee4 from "../assets/images/coffee-img/coffee-4.jpg";
import coffee5 from "../assets/images/coffee-img/coffee-5.jpg";
import coffee6 from "../assets/images/coffee-img/coffee-6.jpg";
import coffee7 from "../assets/images/coffee-img/coffee-7.jpg";
import coffee9 from "../assets/images/coffee-img/coffee-9.jpg";
import coffee10 from "../assets/images/coffee-img/coffee-10.jpg";
import coffee11 from "../assets/images/coffee-img/coffee-11.jpg";
import coffee12 from "../assets/images/coffee-img/coffee-12.jpg";
import coffee13 from "../assets/images/coffee-img/coffee-13.jpg";
import coffee14 from "../assets/images/coffee-img/coffee-14.jpg";
import coffee15 from "../assets/images/coffee-img/coffee-15.jpg";
import coffee16 from "../assets/images/coffee-img/coffee-16.jpg";
import coffee17 from "../assets/images/coffee-img/coffee-17.jpg";
import coffee18 from "../assets/images/coffee-img/coffee-18.jpg";
import coffee19 from "../assets/images/coffee-img/coffee-19.jpg";
import coffee20 from "../assets/images/coffee-img/coffee-20.jpg";
import coffee21 from "../assets/images/coffee-img/coffee-21.jpg";
import coffee22 from "../assets/images/coffee-img/coffee-22.jpg";
import coffee23 from "../assets/images/coffee-img/coffee-23.jpg";
import coffee24 from "../assets/images/coffee-img/coffee-24.png";
import coffee26 from "../assets/images/coffee-img/coffee-26.png";
import coffee27 from "../assets/images/coffee-img/coffee-27.png";
import coffee28 from "../assets/images/coffee-img/coffee-28.png";
import coffee29 from "../assets/images/coffee-img/coffee-29.png";

const coffeeProducts = [
  {
    id: 1,
    name: "Presto Coffee Bags - Smooth Italian",
    description: "Barista-grade coffee bags with a smooth Italian blend.",
    strength: 4,
    size: "40 Coffee Bags",
    weight: "250g",
    bestBefore: "2024-12-31",
    price: 12.99,
    discountPrice: 10.99,
    images: [coffee1, coffee2, coffee3, coffee3, coffee4, coffee5],
    category: "Coffee Bags",
    stock: 100,
    brand: "Presto",
    quantity: 1,
  },
  {
    id: 2,
    name: "Presto Espresso Roast",
    description: "Rich and bold espresso roast for a perfect cup.",
    strength: 5,
    size: "500g",
    weight: "500g",
    bestBefore: "2024-10-01",
    price: 14.99,
    discountPrice: 12.99,
    images: [coffee6, coffee7, coffee9, coffee10, coffee11, coffee12],
    category: "Ground Coffee",
    stock: 50,
    brand: "Presto",
    quantity: 1,
  },
  {
    id: 3,
    name: "Colombian Supremo",
    description: "Smooth and balanced with a hint of chocolate.",
    strength: 3,
    size: "250g",
    weight: "250g",
    bestBefore: "2024-11-15",
    price: 8.99,
    discountPrice: 7.99,
    images: [coffee13, coffee14, coffee15, coffee16, coffee17, coffee18],
    category: "Whole Beans",
    stock: 200,
    brand: "Colombian Gold",
    quantity: 1,
  },
  {
    id: 4,
    name: "Ethiopian Yirgacheffe",
    description: "Floral and fruity with a medium body.",
    strength: 2,
    size: "250g",
    weight: "250g",
    bestBefore: "2025-01-20",
    price: 10.99,
    discountPrice: 9.49,
    images: [coffee19, coffee20, coffee21, coffee22, coffee23, coffee24],
    category: "Whole Beans",
    stock: 120,
    brand: "Ethiopia Prime",
    quantity: 1,
  },
  {
    id: 5,
    name: "French Roast Dark",
    description: "Bold and smoky dark roast.Bold and smoky dark",
    strength: 5,
    size: "1kg",
    weight: "1000g",
    bestBefore: "2025-03-30",
    price: 15.99,
    discountPrice: 13.99,
    images: [coffee26, coffee27, coffee28, coffee29, coffee1, coffee2],
    category: "Ground Coffee",
    stock: 80,
    brand: "Cafe Noir",
    quantity: 1,
  },
  {
    id: 6,
    name: "Guatemala Antigua",
    description: "Rich, spicy, and full-bodied coffee.",
    strength: 4,
    size: "250g",
    weight: "250g",
    bestBefore: "2025-04-10",
    price: 11.99,
    discountPrice: 9.99,
    images: [coffee1, coffee2, coffee3, coffee3, coffee4, coffee5],
    category: "Whole Beans",
    stock: 90,
    brand: "Guatemala Special",
    quantity: 1,
  },
  {
    id: 7,
    name: "Kenya AA",
    description: "Bright acidity with fruity undertones.",
    strength: 3,
    size: "250g",
    weight: "250g",
    bestBefore: "2025-05-20",
    price: 12.49,
    discountPrice: 10.99,
    images: [coffee6, coffee7, coffee9, coffee10, coffee11, coffee12],
    category: "Whole Beans",
    stock: 110,
    brand: "Kenya Finest",
    quantity: 1,
  },
  {
    id: 8,
    name: "Sumatra Mandheling",
    description: "Earthy, full-bodied with a smooth finish.",
    strength: 4,
    size: "250g",
    weight: "250g",
    bestBefore: "2025-06-15",
    price: 13.49,
    discountPrice: 11.99,
    images: [coffee13, coffee14, coffee15, coffee16, coffee17, coffee18],
    category: "Whole Beans",
    stock: 95,
    brand: "Sumatra Choice",
    quantity: 1,
  },
  {
    id: 9,
    name: "Brazil Santos",
    description: "Balanced, smooth, and nutty.Balanced, smooth,",
    strength: 3,
    size: "250g",
    weight: "250g",
    bestBefore: "2025-07-10",
    price: 10.49,
    discountPrice: 8.99,
    images: [coffee19, coffee20, coffee21, coffee22, coffee23, coffee24],
    category: "Ground Coffee",
    stock: 120,
    brand: "Brazil Prime",
    quantity: 1,
  },
  {
    id: 10,
    name: "Honduras Fair Trade Organic",
    description: "Certified organic coffee with a balanced flavor.",
    strength: 3,
    size: "250g",
    weight: "250g",
    bestBefore: "2025-08-30",
    price: 9.99,
    discountPrice: 8.49,
    images: [coffee26, coffee27, coffee28, coffee29, coffee1, coffee2],
    category: "Ground Coffee",
    stock: 140,
    brand: "Honduras Organic",
    quantity: 1,
  },
  {
    id: 11,
    name: "Italian Espresso Blend",
    description: "Classic Italian espresso with bold flavors.",
    strength: 5,
    size: "500g",
    weight: "500g",
    bestBefore: "2025-09-15",
    price: 16.99,
    discountPrice: 14.99,
    images: [coffee1, coffee2, coffee3, coffee3, coffee4, coffee5],
    category: "Ground Coffee",
    stock: 75,
    brand: "Italiano Roast",
    quantity: 1,
  },
  {
    id: 12,
    name: "Peruvian Organic",
    description: "Mild and smooth with a hint of sweetness.",
    strength: 2,
    size: "250g",
    weight: "250g",
    bestBefore: "2025-10-01",
    price: 9.49,
    discountPrice: 7.99,
    images: [coffee6, coffee7, coffee9, coffee10, coffee11, coffee12],
    category: "Whole Beans",
    stock: 130,
    brand: "Peru Natural",
    quantity: 1,
  },
  {
    id: 13,
    name: "Costa Rica Tarrazu",
    description: "Balanced with notes of honey and citrus.",
    strength: 3,
    size: "250g",
    weight: "250g",
    bestBefore: "2025-10-20",
    price: 11.49,
    discountPrice: 9.99,
    images: [coffee6, coffee7, coffee9, coffee10, coffee11, coffee12],

    category: "Whole Beans",
    stock: 115,
    brand: "Costa Special",
    quantity: 1,
  },
  {
    id: 14,
    name: "Mexican Chiapas",
    description: "Smooth with mild acidity and a chocolaty finish.",
    strength: 3,
    size: "250g",
    weight: "250g",
    bestBefore: "2025-11-05",
    price: 10.99,
    discountPrice: 8.99,
    images: [coffee26, coffee27, coffee28, coffee29, coffee1, coffee2],
    category: "Whole Beans",
    stock: 140,
    brand: "Mexicana",
    quantity: 1,
  },
  {
    id: 15,
    name: "Rwanda Gikanda",
    description: "Unique flavor with a touch of berry.",
    strength: 3,
    size: "250g",
    weight: "250g",
    bestBefore: "2025-11-20",
    price: 12.49,
    discountPrice: 10.49,
    images: [coffee13, coffee14, coffee15, coffee16, coffee17, coffee18],
    category: "Whole Beans",
    stock: 90,
    brand: "Rwanda Gold",
    quantity: 1,
  },
];

export default coffeeProducts;
